language: python
python:
- "3.7"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  # - sudo apt-get install -y libspatialindex-dev libgeos-dev gdal-bin
  # - "pip install -U pip"
  # - "python setup.py install"

install:
  - pip install 'pytest>=4.6' pytest-cov coveralls
  - python setup.py develop
  - pip freeze

before_script:
  - git config --global user.email "edward.oughton@gmail.com"
  - git config --global user.name "Edward Oughton"

script:
- pytest --cov india5g --cov-report term-missing

after_success:
  - coveralls

notifications:
  email: false
